### ISSUE TITLE
Data URI to blob is not working, get error: Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by sferoze** [CulturalMe/meteor-slingshot#133]
I am using this function

```coffee
dataURItoBlob = (dataURI) ->
  # convert base64/URLEncoded data component to raw binary data held in a string
  byteString = undefined
  if dataURI.split(',')[0].indexOf('base64') >= 0
    byteString = atob(dataURI.split(',')[1])
  else
    byteString = unescape(dataURI.split(',')[1])
  # separate out the mime component
  mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0]
  # write the bytes of the string to a typed array
  ia = new Uint8Array(byteString.length)
  i = 0
  while i < byteString.length
    ia[i] = byteString.charCodeAt(i)
    i++
  new Blob([ ia ], type: mimeString)
```

and this click handlers

```coffee
'click #fromDevice': (e, t) ->
    MeteorCamera.getPicture (err, data) ->
      console.log data
      blob = dataURItoBlob(data)
      console.log blob
      if blob?
        t.uploader.send blob, (err, downloadUrl) ->
          if err
            Bert.alert err.reason, 'warning'
            console.log err
          else
            Files.insert
              url: downloadUrl
              userId: Meteor.userId()
              type: 'image'

            Bert.alert 'Success, Image added to library', 'success'
```

I am using meteors default camera package. 

This does not work at all. I have tried many various `dataURItoBlob` functions and none of them work. What am I missing? I get a base/64 string image but can't convert to blob

This is the error I get when I try to upload

```
 Exception while invoking method 'slingshot/uploadRequest' TypeError: Cannot call method 'replace' of undefined
I20150914-13:20:17.299(-4)?     at [object Object].Slingshot.createDirective.key (server/slingshot.coffee:28:26)
I20150914-13:20:17.299(-4)?     at Object.Slingshot.S3Storage.upload (packages/edgee:slingshot/services/aws-s3.js:97:1)
I20150914-13:20:17.299(-4)?     at [object Object]._.extend.getInstructions (packages/edgee:slingshot/lib/directive.js:150:1)
I20150914-13:20:17.299(-4)?     at [object Object].Meteor.methods.slingshot/uploadRequest (packages/edgee:slingshot/lib/directive.js:232:1)
I20150914-13:20:17.299(-4)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:164:1)
I20150914-13:20:17.299(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150914-13:20:17.299(-4)?     at packages/ddp/livedata_server.js:648:1
I20150914-13:20:17.299(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150914-13:20:17.299(-4)?     at packages/ddp/livedata_server.js:647:1
I20150914-13:20:17.301(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150914-13:20:17.301(-4)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150914-13:20:17.301(-4)?     at packages/meteorhacks:kadira/lib/hijack/wrap_session.js:52:1
I20150914-13:20:17.301(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150914-13:20:17.301(-4)?     at [object Object].sessionProto.protocol_handlers.method (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:51:1)
I20150914-13:20:17.301(-4)?     at packages/ddp/livedata_server.js:546:1
```

**Comment by sferoze** [comment]
ah gosh USER ERROR

In my directive the key was expecting the file to have a name parameter. 

Files have a name parameter. 

The blob did not. Thus the error.

**Comment by griv** [comment]
Thanks! I was also having this error :) 
#facepalm
