### ISSUE TITLE
cdn key raises errors

### ISSUE THREAD

**Issue by ibussieres** [CulturalMe/meteor-slingshot#160]
The cdn key doesn't seem to work as per documentation. Any hints on this ?

    Slingshot.fileRestrictions("uploads", {
      allowedFileTypes: null,
      cdn: "https://d111111abcdef8.cloudfront.net"
      maxSize: 2 * 1024 * 1024 * 1024 // 2 GB (use null for unlimited)
    });

    Error: Match error: Unknown key in field cdn
        at check (packages/check/match.js:33:1)
        at Object.Slingshot.fileRestrictions (packages/edgee_slingshot/packages/edgee_slingshot.js:36:1)
        at Package (server.js:1:11)
        at /Users/ibussieres/Code/ian/mizinga/.meteor/local/build/programs/server/packages/mizinga_files.js:111:4
        at/Users/ibussieres/Code/ian/mizinga/.meteor/local/build/programs/server/packages/mizinga_files.js:118:3
        at /Users/ibussieres/Code/ian/mizinga/.meteor/local/build/programs/server/boot.js:242:10
        at Array.forEach (native)
        at Function._.each._.forEach (/Users/ibussieres/.meteor/packages/meteor-tool/.1.1.10.986e6d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
        at /Users/ibussieres/Code/ian/mizinga/.meteor/local/build/programs/server/boot.js:137:5

**Comment by onepixelsolid** [comment]
@ibussieres I was just having this issue, but it works fine if you move the `cdn:` key definition within `Slingshot.createDirective` (server side only)

**Comment by iulianpet01** [comment]
@hihellosm  I am able to upload, i see the image in a new tab for the link that is returning.

My problem is  if i put cdn:'https://myDomain.com', when it returns the link, https://myDomain.com/pic.jpg, and i try to view it in a new tab  it shows a empty page. 

so it is working with no cdn, but with cdn is not working.
should i do somethimg else?
