### ISSUE TITLE
TypeError: Object [object Object] has no method 'fileRestrictions'

### ISSUE THREAD

**Issue by x5engine** [CulturalMe/meteor-slingshot#175]
Seriously is this even working?

I am using the last version edgee:slingshot@0.7.1  and getting this error :

```
TypeError: Object [object Object] has no method 'fileRestrictions'
W20160409-21:02:38.387(-4)? (STDERR)     at meteorInstall.node_modules.meteor.nova-upload.lib.server.slingshot.js (packages/tt-upload/lib/server/slingshot.js:4:11)
W20160409-21:02:38.388(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160409-21:02:38.388(-4)? (STDERR)     at require (packages/modules-runtime.js:92:16)
```

is this even working ???

**Comment by ciokan** [comment]
You have to load the `fileRestrictions` directive before the `createDirective` code.
