### ISSUE TITLE
500 error when uploading from staging environment

### ISSUE THREAD

**Issue by DMeechan** [CulturalMe/meteor-slingshot#229]
I've got Slingshot AWS upload successfully working on my dev environment, but it fails whenever I try to upload images from the staging environment (hosted on Heroku). Here's the error I'm getting:

```
details: undefined
error:500
errorType:"Meteor.Error"
isClientSafe:true
message:"Internal server error [500]"
reason:"Internal server error"
```

I had a look at [issue 70](https://github.com/CulturalMe/meteor-slingshot/issues/70) but I don't think it's the same problem, since I'm using the same AWS access keys on the staging environment as I am on the dev environment.

**Comment by DMeechan** [comment]
I found this more helpful error message on the server:

Exception while invoking method 'slingshot/uploadRequest' Error: connect ECONNREFUSED [IP-ADDRESS]:80
t Object._errnoException (util.js:1024:11)
at _exceptionWithHostPort (util.js:1046:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

Any suggestions on what I can do to resolve this?
