### ISSUE TITLE
Version 0.3.0 crashes...?

### ISSUE THREAD

**Issue by Siyfion** [CulturalMe/meteor-slingshot#47]
After upgrading from 0.2.0 to 0.3.0 my meteor application now crashes with the following:

```
W20150112-11:01:00.593(0)? (STDERR) 
W20150112-11:01:00.593(0)? (STDERR) /Users/siyfion/.meteor/packages/meteor-tool/.1.0.38.15hfw32++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150112-11:01:00.594(0)? (STDERR) 						throw(ex);
W20150112-11:01:00.594(0)? (STDERR) 						      ^
W20150112-11:01:00.616(0)? (STDERR) Error: Match error: Unknown key in field domain
W20150112-11:01:00.616(0)? (STDERR)     at packages/check/match.js:299:1
W20150112-11:01:00.617(0)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150112-11:01:00.617(0)? (STDERR)     at checkSubtree (packages/check/match.js:290:1)
W20150112-11:01:00.617(0)? (STDERR)     at check (packages/check/match.js:32:1)
W20150112-11:01:00.617(0)? (STDERR)     at new Slingshot.Directive (packages/edgee:slingshot/lib/directive.js:111:1)
W20150112-11:01:00.617(0)? (STDERR)     at Object.Slingshot.createDirective (packages/edgee:slingshot/lib/directive.js:81:1)
W20150112-11:01:00.617(0)? (STDERR)     at app/server/file_uploads.js:1:46
W20150112-11:01:00.618(0)? (STDERR)     at app/server/file_uploads.js:26:3
W20150112-11:01:00.618(0)? (STDERR)     at /Users/siyfion/Meteor/lll/.meteor/local/build/programs/server/boot.js:175:10
W20150112-11:01:00.618(0)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by gsuess** [comment]
The `domain` parameter to the directive has been removed and replaced by `bucketUrl` and `cdn`. 

https://github.com/CulturalMe/meteor-slingshot/releases/tag/0.3.0

**Comment by Siyfion** [comment]
Ah, I see... Any chance that we could have a `CHANGELOG` file added to the repo, with changes like this in it? Most people (in my experience) don't check the tag notes.

**Comment by gsuess** [comment]
Yea I agree, that should be done and it will be done for 0.4.0. 

Sorry about the inconvenience.

**Comment by gsuess** [comment]
So did that resolve your issue?

**Comment by Siyfion** [comment]
Yup!
