### ISSUE TITLE
createDirective requires maxSize and allowedFileTypes?

### ISSUE THREAD

**Issue by lorensr** [CulturalMe/meteor-slingshot#58]
According to example in README, I have both those fields in a `fileRestrictions` call in `lib/env.js`, and neither in the `createDirective` call in `server/lib/env.js`. I get this error: 

```
W20150123-18:16:49.057(-8)? (STDERR) Error: Match error: Missing key 'maxSize'
W20150123-18:16:49.058(-8)? (STDERR)     at packages/check/match.js:312:1
W20150123-18:16:49.058(-8)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150123-18:16:49.058(-8)? (STDERR)     at checkSubtree (packages/check/match.js:311:1)
W20150123-18:16:49.058(-8)? (STDERR)     at check (packages/check/match.js:32:1)
W20150123-18:16:49.058(-8)? (STDERR)     at new Slingshot.Directive (packages/edgee:slingshot/lib/directive.js:111:1)
W20150123-18:16:49.058(-8)? (STDERR)     at Object.Slingshot.createDirective (packages/edgee:slingshot/lib/directive.js:81:1)
W20150123-18:16:49.058(-8)? (STDERR)     at server/lib/environment.coffee:35:11
W20150123-18:16:49.058(-8)? (STDERR)     at server/lib/environment.coffee:4:1
W20150123-18:16:49.058(-8)? (STDERR)     at /Users/me/Dropbox/Documents/code/parlay/.meteor/local/build/programs/server/boot.js:205:10
W20150123-18:16:49.058(-8)? (STDERR)     at Array.forEach (native)
```
I don't get the error when I add them to `createDirective`.

**Comment by lorensr** [comment]
Looks like the problem might have been that deeper `lib`s get loaded first? Moved the `createDirective` call out of `server/lib` and it works now. Maybe a note on that in Readme?

**Comment by gsuess** [comment]
Agreed, I'll add it to the Readme.

**Comment by Danjavia** [comment]
same error here but not solved when move directive out the server/lib folder? Can you help me please?

**Comment by gsuess** [comment]
@Danjavia you cannot set `GoogleAccessId` in fileRestriction. You must set it in the directive.

**Comment by Danjavia** [comment]
Thanks!!
